### ISSUE TITLE
file path issue 

### ISSUE THREAD

**Issue by tatecarson** [axambo/MIRLC#1]
Hello, 
I was getting an error related to the text file path. I changed line 50 to: 

```
file = File(path.standardizePath ++ date.stamp ++ "_credits" ++ ".txt","w");
```

to fix it. It looks like `.standardizePath` turned `~`into the explicit path `/Users/tatecarson/`. I am not sure why that matters but it seemed to fix the issue. 

I am not sure if this is a platform-specific issue. I am on macOS 10.13.4 and SC version 3.9.3

**Comment by axambo** [comment]
Thanks for the heads up, @tatecarson !
